### ISSUE TITLE
Add contributing file

### ISSUE THREAD

**Issue by Dun-sin** [nishant-ai/TravelGo#12]
Adding the contributing file is useful for new contributors, so they know what to do in this project

Here's a reference link: [Contributing.md](https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by nishant-ai** [comment]
Sure  @Dun-sin! You can start working on it!

**Comment by Dun-sin** [comment]
hi @nishant-ai thanks for assigning me to this, but i would like to give it to anyone who wants it

**Comment by vaibhavmishra4g** [comment]
Could you assign this to me under hacktoberfest label?
