### ISSUE TITLE
Add quick guide

### ISSUE THREAD

**Issue by Dun-sin** [nishant-ai/TravelGo#13]
Add a quick guide on how to run this project in the readme

**Comment by nishant-ai** [comment]
Sure @Dun-sin! Would love to see the updated README! 

Happy Hacking! 🎃

**Comment by Savio629** [comment]
Is this issue still pending or is it closed? @nishant-ai

**Comment by IncredibleZuess** [comment]
Hi @nishant-ai!

Can you assign me to this issue?

Thanks!
