### ISSUE TITLE
Add Animations like Hover.

### ISSUE THREAD

**Issue by nishant-ai** [nishant-ai/TravelGo#2]

**Comment by Erum640** [comment]
please give me this issue

**Comment by Shubh942** [comment]
Hey, @nishant-ai please assign this task to me.

**Comment by Priyanshu85** [comment]
Assign me this issue please!

**Comment by nishant-ai** [comment]
Sure! @Shubh942 @Erum640, Please Start Working and Create PR!

**Comment by VidishaAG** [comment]
Can I work on it please?

**Comment by nishant-ai** [comment]
@VidishaAG! You can start working on it!

**Comment by VidishaAG** [comment]
@nishant-ai Thank you! I will start work on it.
